name: globapp
region: nyc
services:
  # Backend API Service
  - name: api
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: pip install -r requirements.txt
    run_command: uvicorn app:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: GLOBAPP_PUBLIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GLOBAPP_ADMIN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GLOBAPP_JWT_SECRET
        scope: RUN_TIME
        type: SECRET

  # Frontend Static Site
  - name: frontend
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    build_command: npm ci && npm run build
    output_dir: dist
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_BASE_URL
        value: https://globapp.app/api/v1
        scope: BUILD_TIME

